/**
 * MCP Launcher Script Generator.
 *
 * Instead of storing secrets in plaintext in mcp-config.json / ~/.claude.json,
 * we generate a wrapper shell script per MCP server that reads secrets from
 * macOS Keychain at runtime and then execs the actual MCP process.
 *
 * Script location: ~/.pilot/mcp-launchers/<serverId>.sh
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { getPilotDir } from '../config/store.js';

const LAUNCHERS_DIR = 'mcp-launchers';

function getLaunchersDir(): string {
  return path.join(getPilotDir(), LAUNCHERS_DIR);
}

export function getLauncherPath(serverId: string): string {
  return path.join(getLaunchersDir(), `${serverId}.sh`);
}

/**
 * Generates a wrapper shell script that reads secrets from Keychain
 * and launches the MCP server.
 *
 * @param serverId - MCP server ID (e.g. 'gmail', 'slack')
 * @param npmPackage - npm package to run (e.g. '@shinzolabs/gmail-mcp')
 * @param envKeys - Map of ENV_VAR_NAME -> keychain key name
 * @param extraArgs - Additional args after the package name
 * @param nonSecretEnv - Env vars that are NOT secrets (file paths, site names)
 */
export async function generateLauncherScript(
  serverId: string,
  npmPackage: string,
  envKeys: Record<string, string>,
  extraArgs: string[] = [],
  nonSecretEnv: Record<string, string> = {},
): Promise<string> {
  const launcherPath = getLauncherPath(serverId);

  // Ensure directory exists with restricted permissions
  await fs.mkdir(getLaunchersDir(), { recursive: true, mode: 0o700 });

  const lines: string[] = [
    '#!/bin/bash',
    '# Auto-generated by pilot-ai. Do not edit manually.',
    `# MCP launcher for: ${serverId}`,
    '# Secrets are read from macOS Keychain at runtime.',
    '',
  ];

  // Add non-secret env vars directly
  for (const [key, value] of Object.entries(nonSecretEnv)) {
    lines.push(`export ${key}=${shellEscape(value)}`);
  }

  // Add Keychain-backed secret env vars
  for (const [envVar, keychainKey] of Object.entries(envKeys)) {
    lines.push(
      `export ${envVar}=$(security find-generic-password -s ${shellEscape(`pilot-ai:${keychainKey}`)} -a "pilot-ai" -w 2>/dev/null)`,
    );
  }

  if (Object.keys(envKeys).length > 0 || Object.keys(nonSecretEnv).length > 0) {
    lines.push('');
  }

  // exec the MCP server
  const argsStr = extraArgs.length > 0 ? ` ${extraArgs.map(shellEscape).join(' ')}` : '';
  lines.push(`exec npx -y ${shellEscape(npmPackage)}${argsStr}`);
  lines.push('');

  const script = lines.join('\n');
  await fs.writeFile(launcherPath, script, { mode: 0o700 });

  return launcherPath;
}

/**
 * Removes a launcher script for a server.
 */
export async function removeLauncherScript(serverId: string): Promise<void> {
  try {
    await fs.unlink(getLauncherPath(serverId));
  } catch {
    // Not found, ignore
  }
}

/**
 * Checks if a launcher script exists for a server.
 */
export async function hasLauncherScript(serverId: string): Promise<boolean> {
  try {
    await fs.access(getLauncherPath(serverId));
    return true;
  } catch {
    return false;
  }
}

/**
 * Classifies env vars into secrets and non-secrets.
 * Non-secrets: file paths, site names, email addresses, team IDs.
 * Everything else is treated as a secret.
 */
export function classifyEnvVars(
  envValues: Record<string, string>,
): { secrets: Record<string, string>; nonSecrets: Record<string, string> } {
  const secrets: Record<string, string> = {};
  const nonSecrets: Record<string, string> = {};

  for (const [key, value] of Object.entries(envValues)) {
    if (isNonSecretEnvVar(key, value)) {
      nonSecrets[key] = value;
    } else {
      secrets[key] = value;
    }
  }

  return { secrets, nonSecrets };
}

/**
 * Determines if an env var is NOT a secret based on its name and value.
 */
function isNonSecretEnvVar(key: string, value: string): boolean {
  const upperKey = key.toUpperCase();

  // File paths are not secrets
  if (value.startsWith('/') || value.startsWith('~') || value.startsWith('./')) {
    return true;
  }

  // Known non-secret env var patterns
  const nonSecretPatterns = [
    'SITE_NAME', 'USER_EMAIL', 'TEAM_ID',
    '_PATH', '_DIR', '_FILE', '_CONFIG',
  ];
  if (nonSecretPatterns.some((p) => upperKey.includes(p))) {
    return true;
  }

  return false;
}

/**
 * Shell-escapes a string for safe use in a bash script.
 */
function shellEscape(s: string): string {
  // If it's a simple string, just quote it
  if (/^[a-zA-Z0-9_./@:=-]+$/.test(s)) {
    return `"${s}"`;
  }
  // Otherwise, use single quotes with proper escaping
  return `'${s.replace(/'/g, "'\\''")}'`;
}
